---

- hosts: all
  become: true
  tasks:

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Debian" #Only executed when Distro is Debian / Skipped if Distro isnt Debian!

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"] #For both Debian and Ubuntu bc both use apt
